defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: seq_gen_development

test:
  <<: *defaults
  database: seq_gen_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] || 'mongodb://127.0.0.1:27017/seq_gen_development' %>
